language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- iojs
sudo: false
after_script: npm install codecov.io && cat ./coverage/lcov.info | codecov
deploy:
  provider: releases
  api_key:
    secure: bScJUStkdrZ4CLQDqQLrGdNl6vzxChtaRdoOnoWQ1EM5gReCHrm3N8x/vL0VLeWr7dLw3DxrwpqAfYmO8wkpavc4je4F8nSJCjJkRHbOBRJWeMOXcbiqH4HhDvI7unRiYCZ7rL48h/JzsFOy+uB7h/+sOw+kxcB7jG/C9JZ8Twd+zVAtKGNcpB+OICfkwh2GPSGYqi+7hjCxRhxTwv+Pd2DD9E4O1HSGVlxy/e0N1jjsVB1Lcl7p0ogQbjtnRZ1gy6ol1unmsfsFDZ9OGdrDyn73RezEbnIyp/FAY9sCh8bMgPwJxP8+EUcGaDXiH6uJhJ3NgKUlYJv/RpJ0KETQz8jmtFFc32cXahEB1z68mP0abrIvvnRJDx26SRd4SCTcfQ8S2CPrW6yr45vQm4YKD2MC5z/CYT0K/bKhaDCMHuhbo+BWoQVpgN2VCfVfyDdEqoQzlxqOeFe5c/kr3qp37/3RDI319FrCu0iA2t96HjKZadSjzuuUVdB3Ts6RFvdVz2tAg8Ws32MudQrlGznNQ6dlLOrIVAhY9redmKZL5La3pzBaXXgqTt7NRIhhUT4gCYQ0X0UyR1SdVf41UMOQCWR9zejYy0L75ccjsSyJgC0F9UFkZu/mbNKGFa2p+GnE/WoCW1MdyzWMbB7t7F94Oekiz4zlaj2zCHvehp6QkVE=
  file:
    - "remark-slug.js"
    - "remark-slug.min.js"
  on:
    tags: true
